### ISSUE TITLE
IconCompat.createWithResource() Crashes Viewer

### ISSUE THREAD

**Issue by commonsguy** [googlesamples/android-SliceViewer#10]
Tested with [the now-current `1.0.0-alpha03` edition](https://github.com/googlesamples/android-SliceViewer/releases/tag/1.0.0-alpha3) of the Viewer. It *might* just be a discrepancy between what I assume is `1.0.0-alpha03` slice host and a `1.0.0-beta01` slice provider, but I am reporting it in case there is a bigger problem here.

I can crash Slice Viewer by creating a slice using `IconCompat.createWithResource()` for its actions. The stack trace is:

```
2018-07-22 15:25:23.675 3793-3793/com.example.android.sliceviewer E/Icon: Unable to find pkg=com.commonsware.android.slice.dice:drawable/die_3 for icon Icon(typ=RESOURCE pkg=com.commonsware.android.slice.dice:drawable/die_3 id=0x7f060059)
    android.content.pm.PackageManager$NameNotFoundException: com.commonsware.android.slice.dice:drawable/die_3
        at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:378)
        at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:360)
        at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:309)
        at android.graphics.drawable.Icon.loadDrawable(Icon.java:277)
        at androidx.core.graphics.drawable.IconCompat.loadDrawable(IconCompat.java:462)
        at androidx.slice.widget.GridRowView.addItem(GridRowView.java:423)
        at androidx.slice.widget.GridRowView.addCell(GridRowView.java:362)
        at androidx.slice.widget.GridRowView.populateViews(GridRowView.java:258)
        at androidx.slice.widget.GridRowView.access$200(GridRowView.java:65)
        at androidx.slice.widget.GridRowView$1.onPreDraw(GridRowView.java:498)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2349)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

To reproduce it, unZIP, build, and run [SliceAndDiceBug-20180722.zip](https://github.com/googlesamples/android-SliceViewer/files/2217314/SliceAndDiceBug-20180722.zip). Then, view `slice-content://com.commonsware.android.slice.dice.provider` in the Slice Viewer.

The `IconCompat` for the actions is created using a `gimmeAnIcon()` method:

```java
  private IconCompat gimmeAnIcon(Context ctxt, int resId) {
/*
    Bitmap bmp=BitmapFactory.decodeResource(ctxt.getResources(), resId);

    return IconCompat.createWithBitmap(bmp);
*/

    return IconCompat.createWithResource(ctxt, resId);
  }
```

If I use the commented-out code, everything works. If I use `return IconCompat.createWithResource(ctxt, resId);`, I get the aforementioned stack trace, when tested on a Google Pixel 2.

Let me know if you need additional details!

**Comment by KChernenko** [comment]
Hi! I have the same problem with rc01. Any updates?

**Comment by KChernenko** [comment]
I've used a workaround with getting drawable recourse, converting it to bitmap and setting the bitmap via `IconCompat.createWithBitmap(bitmap)`. After updating to `rc02` this approach seems to be broken too - the icon is missing.

**Comment by urvishjarvis1** [comment]
having same issue with rc02

**Comment by adnan-SM** [comment]
Have the same problem with alpha-6 as well

**Comment by codingjeremy** [comment]
@commonsguy or @adnan-SM what version of Android are you running and device are you using? Same to anyone else on the thread.

I am running the SliceViewer with updated libraries for latest on everything (main ones below) and your sample runs for me on Oreo MR1 (Pixel 2). I can try Oreo but I am wondering if it is something else.

I have a sample using IconCompat.createWithResource() on P that works but I can try your sample on that as well if you are seeing it there. I was thinking this was a pre-p bug but I could be wrong. Thanks!

Dependencies:
    implementation "androidx.slice:slice-view:1.0.0"
    implementation "androidx.slice:slice-builders-ktx:1.0.0-alpha6"

**Comment by commonsguy** [comment]
> what version of Android are you running and device are you using?

As noted in [my original comment](https://github.com/googlesamples/android-SliceViewer/issues/10#issue-343432256), it was a Google Pixel 2. At the time (nearly four months ago), it would have been running Android 8.1.

**Comment by adnan-SM** [comment]
@codingjeremy - I am able to reproduce this consistently on a **Nexus 5x** emulator running **API 25**. With the latest libs. 

implementation "androidx.slice:slice-builders-ktx:1.0.0-alpha6" 

Looks like it fails to find the drawable altogether. Stack trace here : https://pastebin.com/zawCdR6j

**Comment by urvishjarvis1** [comment]
@adnan-SM having the same issue with the latest library.
btw I'm using pixel 2xl (android 8.1).

**Comment by adnan-SM** [comment]
@codingjeremy - Looks like the **RC2** apk of Slice viewer fixes this. Just tried running the same code on RC2 and it seems to work fine. 

@urvishjarvis1 - Try downloading the RC2 apk of slice viewer and it should work :)

**Comment by codingjeremy** [comment]
Thanks for verifying, @adnan-SM! I also uploaded a new version of [apk as well](https://github.com/googlesamples/android-SliceViewer/releases/tag/1.0.0), so as long as you use RC2 or the latest, the issue should be resolve. Please reopen if it is not, thanks!
