### ISSUE TITLE
Bug in [androidx.slice:slice-view]:  ShortcutView must crash

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-SliceViewer#7]
The crash happens when `Shortcut` in `SliceViewer` app is selected and the user clicks on the icon of the app which provides slices.

In the other two cases, the crash will not happen.

- For `Shortcut`, we should checkout `ShortcutView.java`, at this handling:
```
    @Override
    public boolean performClick() {
        .....
        if (!callOnClick()) {
            try {
                if (mActionItem != null) {
                    mActionItem.fireAction(null, null);   <------------------------------"Click event" 
                } else {
                   .......
                }
        .....
        return true;
    }
```
- For other cases,  we should checkout `RowView.java`, at this handling:
```
    @Override
    public void onClick(View view) {
        if (mRowAction != null && mRowAction.getActionItem() != null) {
               ......
            } else {
                try {
                    mRowAction.getActionItem().fireAction(null, null); <------------------------------"Click event" 
                   .......
                } catch (CanceledException e) {
                    Log.e(TAG, "PendingIntent for slice cannot be sent", e);
                }
            }
        }
    }
```

- Both `ActionItem` which call `fireAction()` are `SliceItem`: 
```
    public void fireAction(@Nullable Context context, @Nullable Intent i)
            throws PendingIntent.CanceledException {
        Object action = ((Pair<Object, Slice>) mObj).first;  
        .......
    }
```
That means `ActionItem` must contain `mObj` which is `Pair<Object, Slice>`.
- Crash:
```
java.lang.ClassCastException: androidx.core.graphics.drawable.IconCompat cannot be cast to androidx.core.util.Pair
        at androidx.slice.SliceItem.fireAction(SliceItem.java:231)
        at androidx.slice.widget.ShortcutView.performClick(ShortcutView.java:131)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25883)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by commonsguy** [comment]
This is not a bug in the Slice Viewer app -- it is a bug somewhere in the `slice-view` code. I reproduced it [in another slice hosting app](https://issuetracker.google.com/issues/111707641).

**Comment by codingjeremy** [comment]
@XinyueZ - the issue should be resolve in the latest library now (which is now included in the latest [apk build for this sample](https://github.com/googlesamples/android-SliceViewer/releases)). 

@commonsguy - thanks for logging the bug!
